import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Cinzel_Decorative } from "next/font/google"; // 👈 1. Import the new font
import "./globals.css";

// 2. Load the Cinzel Decorative font
const cinzelDecorative = Cinzel_Decorative({
  weight: '700',
  subsets: ["latin"],
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TLCCRM Youth Choir Song App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Remove the <link> tag from the <head> */}
      <body className={`${geistSans.variable} ${geistMono.variable} ${cinzelDecorative.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
